name: Syncer Docker image CI
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
     - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yeyus/nhkeva-syncer
  WORKING_DIR: ./syncer
  
jobs:
  build-and-checkout:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install modules
      working-directory: ${{ env.WORKING_DIR }}
      run: npm install
      
    - name: Run tests
      working-directory: ${{ env.WORKING_DIR }}
      run: npm run test

    - name: Registry Login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./syncer
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
